import { expect } from 'chai';
import sinon from 'sinon';
import { shallowMountWithRouting } from './test-utils';
import AboutMonarch from '@/views/AboutMonarch.md';
import AboutTeam from '@/views/AboutTeam.md';

const teamResponse = {
  data:
`####
#### Information file containing institution and member information
#### for the monarch project.
#### Still needs to be a little spiffier--the template is bare bones.
#### Changes from the old page are TOC,
#### optional people pictures and contact info, and YAML-driven.
#### The institution/people information is now stored in conf/monarch-team.yaml.
#### There should be no monarch-team.json file stored in GitHub.
#### It is generated by gulp build from the monarch-team.yaml file.
#### People can also check that the YAML file is correct with kwalify and
#### conf/monarch-team.schema.yaml.


####
institutions:
  - id: ohsu
    name: Oregon Health & Science University
    logo: img/team/ohsu.gif
    website: http://ohsu.edu
    people:
      - name: Melissa Haendel
        picture: img/team/MelissaHaendel.jpg
        title: Monarch PI
        alumni: false
        bio: Dr. Haendel is currently a PI of the Monarch Initiative. She has a BA from Reed College in Chemistry and a Ph.D. in Neuroscience from the University of Wisconsin, Madison. She is currently a PI of the Monarch Initiative, with the aim of providing integrated access to model systems phenotype-genotype data for the purposes of disease hypothesis exploration. She also participates in development of the eagle-i and CTSAconnect ontologies, designed to collect and disseminate information about biomedical resources and enable research profiling. Her research interests are in using ontologies to promote synthetic science though connections within biomedical data, to utilize information science during the course of research and its publication, and to enable scientific reproducibility.
`
};

// Fixing the:
//  Unknown custom element: <router-link>
// warning...
// See: https://stackoverflow.com/a/50639123/5667222
//

describe('AboutMonarch.md', () => {
  it('renders "Our philosophy"', () => {
    const wrapper = shallowMountWithRouting(AboutMonarch);
    expect(wrapper.text()).to.include('Our philosophy');
  });
});


const mockAxios = {
  get: sinon.stub()
    .withArgs(`${process.env.BASE_URL}team.yaml`)
    .returns(Promise.resolve(teamResponse))
};

describe('AboutTeam.md', () => {
  it('renders "Participating Institutions"', () => {
    const wrapper = shallowMountWithRouting(AboutTeam, {
      mocks: {
        $http: mockAxios
      }
    });
    expect(wrapper.text()).to.include('Participating Institutions');
  });
});
