name: Deploy Production

# when someone merges a pull request or commits to master
on:
  push:
    branches:
      - master

# deploy to github pages
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: "14"
      - name: Install packages
        run: yarn install
      - name: Build app
        run: yarn build
      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          keep_files: false
          publish_dir: ./dist
          publish_branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}
