name: Test Pull Request

# when someone submits a pull request
on: pull_request

# make sure tests pass and app can build successfully
jobs:
  test-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install packages
        run: npm install
      - name: Test code
        run: npm run test:unit
      - name: Lint code
        run: npm run lint
      - name: Build app
        run: npm run build
